# Generated by Django 4.1.7 on 2023-04-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_plan'),
        ('lead', '0005_leadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_files', to='team.team'),
        ),
    ]
